apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  {{- include "lokalsifront.namespace" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.pod.labels | nindent 6 }}
  replicas: 2
  template:
    metadata:
      labels: 
        {{- toYaml .Values.pod.labels | nindent 8 }}
    spec:
      containers:
        - name: lokalsi-front
          image: {{ template "lokalsifront.imageUrl" . }}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 2
          ports:
            {{- toYaml .Values.pod.ports | nindent 12 }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"