apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourcequota.name }}
  {{- include "lokalsifront.namespace" . | nindent 2 }}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 1Gi