apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourcequota.name }}
  {{- include "lokalsifront.namespace" . | nindent 2 }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi