version: 2
jobs:
  build:
    working_directory: ~/lokalsi/front
    steps:
      - checkout:
          path: ~/lokalsi
      - setup_remote_docker:
          version: docker:19.03.13
      - run:
          name: Build application Docker image
          command: docker build -t lokalsi-front .