version: 2.1
orbs:
  node: circleci/node@5.0.1
  gcp-gke: circleci/gcp-gke@1.4.0
  gcp-gcr: circleci/gcp-gcr@0.14.1
jobs:
  build-and-push-docker-image:
    working_directory: ~/lokalsi/front
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout:
          path: ~/lokalsi
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Login Into Repository
          command: docker login -u _json_key -p "$(echo $GCLOUD_SERVICE_KEY)" https://europe-central2-docker.pkg.dev
      - run:
          name: Build Image
          command: docker build -t europe-central2-docker.pkg.dev/$GCP_PROJECT_ID/lokalsi/lokalsi-front:${CIRCLE_SHA1:0:7} .
      - run:
          name: Push Image
          command: docker push europe-central2-docker.pkg.dev/$GCP_PROJECT_ID/lokalsi/lokalsi-front:${CIRCLE_SHA1:0:7}
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install
      # Initialize the `gcloud` CLI.
      - gcp-gke/init
      # Update a deployment Docker image.
      - gcp-gke/rollout-image:
          deployment: lokalsi-front-deployment
          container: lokalsi-front
          namespace: lokalsi-front
          cluster: lokalsi-cluster-1
          image: europe-central2-docker.pkg.dev/$GCP_PROJECT_ID/lokalsi/lokalsi-front:${CIRCLE_SHA1:0:7} 
workflows:
  build_update_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build