version: 2.1
jobs:
  build-webapp:
    working_directory: ~/lokalsi/front
    docker:
      - image: node:17.3.0-alpine
    environment:
      - NODE_ENV: 'production'
      - CI: 'false'
    steps:
      - checkout:
          path: ~/lokalsi
      - run:
          name: "Install Dependencies"
          command: |
            npm ci --only=production
            npm install react-scripts@5.0.0 -g --silent
      - run:
          name: "Build"
          command: npm run build
      - persist_to_workspace:
          root: . 
          paths: 
           - build
           - Dockerfile
  build-and-push-docker-image:
    working_directory: ~/lokalsi/front
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - attach_workspace: 
          at: .
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Login Into Repository
          command: docker login -u _json_key -p "$(echo $GCLOUD_SERVICE_KEY)" https://europe-central2-docker.pkg.dev
      - run:
          name: Build Image
          command: docker build -t europe-central2-docker.pkg.dev/$GCP_PROJECT_ID/lokalsi/lokalsi-front:${CIRCLE_SHA1:0:7} .
      - run:
          name: Push Image
          command: docker push europe-central2-docker.pkg.dev/$GCP_PROJECT_ID/lokalsi/lokalsi-front:${CIRCLE_SHA1:0:7}
  auth-to-cluster:
    docker:
      - image: google/cloud-sdk:377.0.0
    description: "Authenticate to GKE Cluster"
    environment:
      - GKE_CLUSTER_NAME: 'lokalsi-cluster-1'
    steps:
      - run:
          name: "Setup Google Cloud SDK"
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/region ${GOOGLE_COMPUTE_REGION}
            gcloud --quiet container clusters get-credentials ${GKE_CLUSTER_NAME}
      - persist_to_workspace:
          root: . 
          paths: 
           - ~/.kube/config
  deploy-to-cluster:
    docker:
      - image: google/cloud-sdk:377.0.0
    description: "Deploy application to GKE Cluster"
    environment:
      - K8S_DEPLOYMENT_NAME: 'lokalsi-front-deployment'
      - K8S_NAMESPACE_NAME: 'lokalsi-front'
    steps:
      - attach_workspace: 
          at: ~/.kube
      - run:
          name: "Update Container Version"
          command: kubectl set image deployment ${K8S_DEPLOYMENT_NAME} -n ${K8S_NAMESPACE_NAME} lokalsi-front=europe-central2-docker.pkg.dev/$GCP_PROJECT_ID/lokalsi/lokalsi-front:${CIRCLE_SHA1:0:7}
workflows:
  build-and-deploy:
    jobs:
      - build-webapp
      - build-and-push-docker-image:
          requires:
            - build-webapp
      - auth-to-cluster:
          required:
            - build-and-push-docker-image
      - deploy-to-cluster:
          requires:
            - auth-to-cluster