apiVersion: v1
kind: ResourceQuota
metadata:
  name: lokalsi-front-resourcequota
  namespace: lokalsi-front
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi